/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apple_dnssd_AppleDNSSD */

#ifndef _Included_com_apple_dnssd_AppleDNSSD
#define _Included_com_apple_dnssd_AppleDNSSD
#ifdef __cplusplus
extern "C" {
#endif
#undef com_apple_dnssd_AppleDNSSD_MORE_COMING
#define com_apple_dnssd_AppleDNSSD_MORE_COMING 1L
#undef com_apple_dnssd_AppleDNSSD_DEFAULT
#define com_apple_dnssd_AppleDNSSD_DEFAULT 4L
#undef com_apple_dnssd_AppleDNSSD_NO_AUTO_RENAME
#define com_apple_dnssd_AppleDNSSD_NO_AUTO_RENAME 8L
#undef com_apple_dnssd_AppleDNSSD_SHARED
#define com_apple_dnssd_AppleDNSSD_SHARED 16L
#undef com_apple_dnssd_AppleDNSSD_UNIQUE
#define com_apple_dnssd_AppleDNSSD_UNIQUE 32L
#undef com_apple_dnssd_AppleDNSSD_BROWSE_DOMAINS
#define com_apple_dnssd_AppleDNSSD_BROWSE_DOMAINS 64L
#undef com_apple_dnssd_AppleDNSSD_REGISTRATION_DOMAINS
#define com_apple_dnssd_AppleDNSSD_REGISTRATION_DOMAINS 128L
#undef com_apple_dnssd_AppleDNSSD_MAX_DOMAIN_NAME
#define com_apple_dnssd_AppleDNSSD_MAX_DOMAIN_NAME 1009L
#undef com_apple_dnssd_AppleDNSSD_ALL_INTERFACES
#define com_apple_dnssd_AppleDNSSD_ALL_INTERFACES 0L
#undef com_apple_dnssd_AppleDNSSD_LOCALHOST_ONLY
#define com_apple_dnssd_AppleDNSSD_LOCALHOST_ONLY -1L
/*
 * Class:     com_apple_dnssd_AppleDNSSD
 * Method:    ConstructName
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleDNSSD_ConstructName
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     com_apple_dnssd_AppleDNSSD
 * Method:    ReconfirmRecord
 * Signature: (IILjava/lang/String;II[B)V
 */
JNIEXPORT void JNICALL Java_com_apple_dnssd_AppleDNSSD_ReconfirmRecord
  (JNIEnv *, jobject, jint, jint, jstring, jint, jint, jbyteArray);

/*
 * Class:     com_apple_dnssd_AppleDNSSD
 * Method:    GetNameForIfIndex
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apple_dnssd_AppleDNSSD_GetNameForIfIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_apple_dnssd_AppleDNSSD
 * Method:    GetIfIndexForName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleDNSSD_GetIfIndexForName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_apple_dnssd_AppleDNSSD
 * Method:    InitLibrary
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleDNSSD_InitLibrary
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_apple_dnssd_AppleBrowser */

#ifndef _Included_com_apple_dnssd_AppleBrowser
#define _Included_com_apple_dnssd_AppleBrowser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleBrowser
 * Method:    CreateBrowser
 * Signature: (IILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleBrowser_CreateBrowser
  (JNIEnv *, jobject, jint, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_apple_dnssd_AppleResolver */

#ifndef _Included_com_apple_dnssd_AppleResolver
#define _Included_com_apple_dnssd_AppleResolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleResolver
 * Method:    CreateResolver
 * Signature: (IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleResolver_CreateResolver
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_apple_dnssd_AppleRegistration */

#ifndef _Included_com_apple_dnssd_AppleRegistration
#define _Included_com_apple_dnssd_AppleRegistration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleRegistration
 * Method:    BeginRegister
 * Signature: (IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I[B)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleRegistration_BeginRegister
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jstring, jstring, jint, jbyteArray);

/*
 * Class:     com_apple_dnssd_AppleRegistration
 * Method:    AddRecord
 * Signature: (II[BILcom/apple/dnssd/AppleDNSRecord;)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleRegistration_AddRecord
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_apple_dnssd_AppleQuery */

#ifndef _Included_com_apple_dnssd_AppleQuery
#define _Included_com_apple_dnssd_AppleQuery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleQuery
 * Method:    CreateQuery
 * Signature: (IILjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleQuery_CreateQuery
  (JNIEnv *, jobject, jint, jint, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_apple_dnssd_AppleDomainEnum */

#ifndef _Included_com_apple_dnssd_AppleDomainEnum
#define _Included_com_apple_dnssd_AppleDomainEnum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleDomainEnum
 * Method:    BeginEnum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleDomainEnum_BeginEnum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_apple_dnssd_AppleService */

#ifndef _Included_com_apple_dnssd_AppleService
#define _Included_com_apple_dnssd_AppleService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleService
 * Method:    BlockForData
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleService_BlockForData
  (JNIEnv *, jobject);

/*
 * Class:     com_apple_dnssd_AppleService
 * Method:    ProcessResults
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleService_ProcessResults
  (JNIEnv *, jobject);

/*
 * Class:     com_apple_dnssd_AppleService
 * Method:    HaltOperation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apple_dnssd_AppleService_HaltOperation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_apple_dnssd_AppleDNSRecord */

#ifndef _Included_com_apple_dnssd_AppleDNSRecord
#define _Included_com_apple_dnssd_AppleDNSRecord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleDNSRecord
 * Method:    Update
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleDNSRecord_Update
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_apple_dnssd_AppleDNSRecord
 * Method:    Remove
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleDNSRecord_Remove
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_apple_dnssd_AppleRecordRegistrar */

#ifndef _Included_com_apple_dnssd_AppleRecordRegistrar
#define _Included_com_apple_dnssd_AppleRecordRegistrar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apple_dnssd_AppleRecordRegistrar
 * Method:    CreateConnection
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleRecordRegistrar_CreateConnection
  (JNIEnv *, jobject);

/*
 * Class:     com_apple_dnssd_AppleRecordRegistrar
 * Method:    RegisterRecord
 * Signature: (IILjava/lang/String;II[BILcom/apple/dnssd/AppleDNSRecord;)I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_AppleRecordRegistrar_RegisterRecord
  (JNIEnv *, jobject, jint, jint, jstring, jint, jint, jbyteArray, jint, jobject);

  /*
 * Class:     com_apple_dnssd_DNSSDEmbedded
 * Method:    Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_DNSSDEmbedded_Init
  (JNIEnv *, jclass);


  /*
 * Class:     com_apple_dnssd_DNSSDEmbedded
 * Method:    Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_apple_dnssd_DNSSDEmbedded_Loop
  (JNIEnv *, jclass);  

/*
 * Class:     com_apple_dnssd_DNSSDEmbedded
 * Method:    Exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_apple_dnssd_DNSSDEmbedded_Exit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
